### PR TITLE
make changes according to new pack cmd

### PR DESCRIPTION
**Pull request by haliliceylan**
According to https://github.com/buildpacks/docs/pull/376 and https://github.com/buildpacks/docs/issues/307, `pack buildpacks new` command is added.

Changes:
- Buildpack Author Guide / Building Blocks CNB Page is edited.

I did not test on my local, not figure out how i can test.

### CODE REVIEW

**Comment by haliliceylan** [comment]
Maybe we need to wait buildpacks/docs#376. Because it can be need some changes.

**Comment by haliliceylan** [comment]
I am converting to draft, until docs PR complete.

**Comment by haliliceylan** [comment]
@samj1912, i checked tutorial, its seems good. I updated according to latest comments on docs PR. You can check from here, its my fork. https://www.katacoda.com/haliliceylan/scenarios/buildpack-author-guide

**Review by samj1912 — APPROVED** [review]
LGTM - will merge once the docs PR is merged

**Pull request merged**
